trigger:
  - main  # Trigger pipeline on changes to the main branch

pool:
  name: Default  # Assuming you're using the default agent pool (self-hosted or Microsoft-hosted)

variables:
  mysqlHost: 'localhost'  # Use your MySQL server's public IP or hostname
  mysqlUser: 'root'  # MySQL user
  mysqlPassword: $(MYSQL_PASSWORD)  # Secure variable for the MySQL password
  databaseName: 'my_database'  # Database name
  sqlRepo: 'https://github.com/Sameer4795/mysql-scripts.git'  # GitHub repository for SQL scripts
  sqlFile: 'setup.sql'  # SQL file to execute

steps:
  - checkout: self  # Fetch the repository containing the SQL script
  
  - script: |
      echo "Cloning MySQL scripts repository from GitHub..."
      git clone $(sqlRepo) $(Build.SourcesDirectory)/mysql-scripts  # Clone the repo containing your SQL scripts
    displayName: 'Clone MySQL Scripts Repository'

  - script: |
      echo "Installing MySQL client..."
      sudo apt-get update
      sudo apt-get install mysql-client -y  # Install MySQL client if not already installed
    displayName: 'Install MySQL Client'

  - script: |
      echo "Running SQL script..."
      mysql -h $(mysqlHost) -u $(mysqlUser) -p$(mysqlPassword) $(databaseName) < $(Build.SourcesDirectory)/mysql-scripts/$(sqlFile)  # Run the SQL script
    displayName: 'Run SQL Script'
    condition: succeeded()  # Only run if previous steps succeed
