trigger:
  - main  # Trigger pipeline on changes to the main branch

pool:
  name: Default  # Using the default agent pool

variables:
  mysqlHost: 'localhost'
  mysqlUser: 'root'
  mysqlPassword: $(MYSQL_PASSWORD)
  databaseName: 'my_database'
  backupFile: '$(Build.ArtifactStagingDirectory)/mysql_backup.sql'

steps:
  # ✅ Step 1: Backup MySQL Database
  - script: |
      echo "Taking MySQL database backup..."
      mysqldump -h $(mysqlHost) -u $(mysqlUser) --password=$(mysqlPassword) $(databaseName) > $(backupFile)

      echo "Verifying backup file..."
      ls -lh $(backupFile)
    displayName: 'Backup MySQL Database'

  # ✅ Step 2: Upload Backup to Artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(backupFile)'
      artifactName: 'MySQLBackup'
    displayName: 'Upload MySQL Backup to Artifacts'

  # ✅ Step 3: Download Backup from Artifacts (For Recovery)
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      artifactName: 'MySQLBackup'
      downloadPath: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Download MySQL Backup from Artifacts'

  # ✅ Step 4: Restore Database from Backup
  - script: |
      echo "Restoring MySQL database from backup..."
      mysql -h $(mysqlHost) -u $(mysqlUser) --password=$(mysqlPassword) $(databaseName) < $(Build.ArtifactStagingDirectory)/mysql_backup.sql

      echo "Verifying restored database..."
      mysql -h $(mysqlHost) -u $(mysqlUser) --password=$(mysqlPassword) -e "SHOW TABLES;" $(databaseName)
    displayName: 'Restore MySQL Database'
