trigger:
- main  # You can replace 'main' with your branch name

pool:
  name: 'Default'  # Using the default agent pool

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'sam'  # Replace with your Azure service connection name
    KeyVaultName: 'SameerKeyVault'                       # Replace with your Key Vault name
    SecretsFilter: '*'                                  # Fetch all secrets, or specify specific secrets like 'mysql-password, mysql-connection-string'
    RunAsPreJob: false

- script: |
    echo $(mysql-password)
    echo $(mysql-connection-string)
  displayName: 'Print the secrets'
