trigger:
- main

pool:
  name: Default  # Use your self-hosted agent pool name

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'a'  # Use your service connection here
    keyVaultName: 'SameerKeyVaultt'
    secretsFilter: 'MySecret'  # Specify the secret name you want to fetch
  name: FetchSecrets

- script: echo $(MySecret)
  displayName: 'Print MySecret'
