trigger:
- main

pool:
  name: default  # Your agent pool

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'sam'
    KeyVaultName: 'SameerKeyVault'
    SecretsFilter: '*'
    RunAsPreJob: false
