- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'a'
    KeyVaultName: 'SameerKeyVaultt'
    SecretsFilter: 'MySecret'
    RunAsPreJob: false

- script: |
    echo "$(MySecret)" > secret.txt
  displayName: 'Save secret to file'
