trigger:
- main  # Change to your branch name

pool:
  vmImage: 'ubuntu-latest'  # Use a self-hosted agent if MySQL is on-premises

variables:
  mysqlHost: "your-mysql-host"  # Use localhost if MySQL is on your machine
  mysqlUser: "your-mysql-user"
  mysqlPassword: "$(MYSQL_PASSWORD)"  # Store in Azure DevOps secret variables
  databaseName: "your-database"
  backupFile: "$(Build.ArtifactStagingDirectory)/db_backup.sql"
  sqlRepo: "Sameer4795/mysql-scripts"
  sqlScriptsPath: "$(Build.SourcesDirectory)/mysql-scripts"

steps:
- checkout: self  # Fetches the main repository

- script: |
    echo "Cloning SQL scripts repository..."
    git clone https://github.com/Sameer4795/mysql-scripts.git $(sqlScriptsPath)
  displayName: 'Clone SQL Scripts Repo'

- script: |
    echo "Creating MySQL backup..."
    mysqldump -h $(mysqlHost) -u $(mysqlUser) -p$(mysqlPassword) $(databaseName) > $(backupFile)
  displayName: 'Backup MySQL Database'

- script: |
    echo "Deploying SQL scripts..."
    for file in $(sqlScriptsPath)/*.sql; do
      echo "Executing $file"
      mysql -h $(mysqlHost) -u $(mysqlUser) -p$(mysqlPassword) $(databaseName) < "$file"
    done
  displayName: 'Run SQL Scripts'
  continueOnError: true  # Allow failure detection

- script: |
    echo "Deployment failed. Restoring backup..."
    mysql -h $(mysqlHost) -u $(mysqlUser) -p$(mysqlPassword) $(databaseName) < $(backupFile)
  displayName: 'Rollback on Failure'
  condition: failed()
